services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - MODEL=$MODEL
      - API_KEY=$API_KEY
